# Generated by Django 3.0.5 on 2020-05-17 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Choices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jersey', models.CharField(default='jersey', max_length=30)),
                ('fh', models.CharField(default='fh', max_length=30)),
            ],
        ),
        migrations.RemoveField(
            model_name='farmerprofile',
            name='Breed_type',
        ),
        migrations.AlterField(
            model_name='farmerprofile',
            name='Phone_number',
            field=models.BigIntegerField(max_length=10),
        ),
        migrations.AlterField(
            model_name='farmerprofile',
            name='Size_of_farm',
            field=models.IntegerField(),
        ),
        migrations.AddField(
            model_name='farmerprofile',
            name='Breed_type',
            field=models.ManyToManyField(to='home.Choices'),
        ),
    ]
