# Generated by Django 3.0.5 on 2020-05-17 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20200517_1346'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farmerprofile',
            name='Breed_type',
        ),
        migrations.AddField(
            model_name='farmerprofile',
            name='Gir',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='farmerprofile',
            name='Holstein_Friesian',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='farmerprofile',
            name='Jersey',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='farmerprofile',
            name='Khillar',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='farmerprofile',
            name='Others',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='farmerprofile',
            name='Sahiwal',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.DeleteModel(
            name='Choices',
        ),
    ]
