# Generated by Django 3.0.5 on 2020-05-31 04:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20200528_2006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmerprofile',
            name='Installed_date',
            field=models.DateField(default=datetime.date(2020, 5, 31)),
        ),
    ]
