# Generated by Django 3.0.5 on 2020-05-17 10:37

from django.db import migrations
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20200517_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmerprofile',
            name='Phone_number',
            field=phone_field.models.PhoneField(max_length=31),
        ),
    ]
