# Generated by Django 3.0.5 on 2020-05-17 10:47

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20200517_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmerprofile',
            name='Phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True),
        ),
    ]
