# Generated by Django 3.0.5 on 2020-05-17 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_farmerprofile_mooma_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmerprofile',
            name='Mooma_user_id',
            field=models.BigIntegerField(),
        ),
    ]
