# Generated by Django 3.0.5 on 2020-05-17 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20200517_1957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmerprofile',
            name='Mooma_user_id',
            field=models.IntegerField(),
        ),
    ]
