# Generated by Django 3.0.5 on 2020-05-18 15:37

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_farmerprofile_installed_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='farmerprofile',
            name='Installed_date',
            field=models.DateField(default=datetime.date(2020, 5, 18)),
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Country')),
            ],
        ),
        migrations.AddField(
            model_name='farmerprofile',
            name='City',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.City'),
        ),
        migrations.AddField(
            model_name='farmerprofile',
            name='Country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.Country'),
        ),
    ]
