# Generated by Django 3.0.5 on 2020-05-18 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_auto_20200518_2107'),
    ]

    operations = [
        migrations.RenameField(
            model_name='farmerprofile',
            old_name='City',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='farmerprofile',
            old_name='Country',
            new_name='country',
        ),
    ]
