# Generated by Django 3.0.5 on 2020-05-19 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_auto_20200519_1548'),
    ]

    operations = [
        migrations.RenameField(
            model_name='farmerprofile',
            old_name='sub_district',
            new_name='subdistrict',
        ),
    ]
