# Generated by Django 3.0.5 on 2020-05-19 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_auto_20200519_1630'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pincode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('subdistrict', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.SubDistrict')),
            ],
        ),
        migrations.AddField(
            model_name='farmerprofile',
            name='pincode',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.Pincode'),
        ),
    ]
