# Generated by Django 3.0.5 on 2020-05-23 13:15

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0015_auto_20200519_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmerprofile',
            name='Installed_date',
            field=models.DateField(default=datetime.date(2020, 5, 23)),
        ),
        migrations.CreateModel(
            name='FinancierProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_confirmed', models.BooleanField(default=False)),
                ('Mooma_user_id', models.IntegerField()),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('Address', models.CharField(max_length=300)),
                ('Phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True)),
                ('Size_of_farm', models.IntegerField()),
                ('Equipment_used', models.CharField(max_length=300)),
                ('Installed_date', models.DateField(default=datetime.date(2020, 5, 23))),
                ('Jersey', models.BooleanField(blank=True, default=False)),
                ('Holstein_Friesian', models.BooleanField(blank=True, default=False)),
                ('Sahiwal', models.BooleanField(blank=True, default=False)),
                ('Khillar', models.BooleanField(blank=True, default=False)),
                ('Gir', models.BooleanField(blank=True, default=False)),
                ('Other_breed', models.CharField(blank=True, max_length=200)),
                ('Mixed_breed', models.CharField(blank=True, max_length=200)),
                ('district', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.District')),
                ('pincode', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.Pincode')),
                ('state', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.State')),
                ('subdistrict', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.SubDistrict')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
