# Generated by Django 3.0.5 on 2020-05-24 09:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='farmerprofile',
            name='Installed_date',
            field=models.DateField(default=datetime.date(2020, 5, 24)),
        ),
        migrations.AlterField(
            model_name='financierprofile',
            name='Installed_date',
            field=models.DateField(default=datetime.date(2020, 5, 24)),
        ),
    ]
