# Generated by Django 3.0.5 on 2020-05-24 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_auto_20200524_1438'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
