# Generated by Django 3.0.5 on 2020-05-24 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmerprofile',
            name='is_farmer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='financierprofile',
            name='is_financier',
            field=models.BooleanField(default=False),
        ),
    ]
