# Generated by Django 3.0.5 on 2020-05-24 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_auto_20200524_1648'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
